### ISSUE TITLE
preinstall script fails

### ISSUE THREAD

**Issue by lunelson** [mechio/grunt-takana#4]
Tried to `npm install` grunt-takana via a package.json file and was told that this failed:

`npm i -g takana && takana sublime:install`

The thing is I already did those anyway, and I also have the GUI app on my system too. What's the current way to do this?

**Comment by ghost** [comment]
i'm getting the same:

```
npm ERR! Failed at the grunt-takana@1.0.4 preinstall script.
npm ERR! This is most likely a problem with the grunt-takana package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm i -g takana && takana sublime:install
```

**Comment by jonstuebe** [comment]
Anyone found a solution? I'm getting the same error. Looks like it needs to be run as root

**Comment by matt-bailey** [comment]
I'm having the same problem too (regular and root).

I've tried installing the grunt task through the command line, `npm install grunt-takana --save-dev`, and by adding `"grunt-takana": "^1.0.4",` directly to `package.json` and running `npm install.`

I'm in a Vagrant VM (Ubuntu), don't know if that makes a difference? So everything is running in the VM apart from Sublime, which is running on my host machine (the VM and host machine sync my project folder).

**Comment by sunilw** [comment]
I'm getting this as well.  
If it's useful; I'm using grunt v0.4.5,  node -v v0.10.32,  npm -v 1.4.28

full error dump here:
https://gist.github.com/sunilw/6fdea64f3974e793f2ba

**Comment by AdelDima** [comment]
i'm getting the same

**Comment by shealan** [comment]
Is this a dead project? I can't seem to install - getting similar errors as above. Would be such a shame as when this works it's incredible.
